@startuml lsp
class Duck {
  +quack()
  +swim()
}

class ElectronicDuck {
  -_on: boolean
  +quack() throws Exception
  +swim() throws Exception
  +turnOn()
  +turnOff()
}

class Pool {
  +run()
  +quack(Duck...)
  +swim(Duck...)
  +main(String[])
}

Duck <|-- ElectronicDuck
Pool -> Duck
@enduml
