@startuml dip
class EncodingModule {
  +encodeWithFiles() throws IOException
  +encodeBasedOnNetworkAndDatabase() throws IOException
}

class MyDatabase {
  -_data : Map<Integer, String>
  -_count : int
  +write(inputString : String) : int
}

MyDatabase <-- EncodingModule
@enduml
